### ISSUE TITLE
Afbeelding gestretched

### ISSUE THREAD

**Issue by Theo-denBlanken** [sohilalami/jQuary#1]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
<img alt="Kid Cudi" src="images/3.jpg" height="300" width="300"> 
```

URL: https://github.com/sohilalami/jQuary/blob/master/jquery/index.html

Feedback: je kunt: 
óf breedte óf hoogte vrijlaten

óf de afbeeldingen in PhotoShop vooraf de juiste afmetingen/verhoudingen geven

óf de afbeelding bijsnijden:
https://dev.to/teroauralinna/crop-and-resize-images-with-css-444h

https://alligator.io/css/cropping-images-object-fit/

https://www.calliaweb.co.uk/hard-soft-crop/[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"4df8eb5f17dca02f0f9e0d1727e628fe84c8fe72","path":"jquery/index.html","reviewer":"Theo-denBlanken"}')

**Comment by sohilalami** [comment]
Afbeelding is niet meer gestreched
